package com.whitewoodcity.xtrike.fxgl.entity;

public enum Type {
  TESSA,CLANCY,
  LOCOMOTIVE, CART,
  PLAYER, BULLET, TANK_M7, TANK_M7_SHELL, LAUNCHER,
  HELICOPTER_APACHE, HELICOPTER_APACHE_MISSILE, LAUNCHER_MISSILE,
  LATV, BATTLESHIP_SIEGFRIED, LASER_BEAM, BATTLESHIP_YAMATO, BATTLESHIP_YAMATO_MISSILE,
  BATTLESHIP_YAMATO_SHELL, F3, F3_MISSILE, BATTLESHIP_FENRIR, BATTLESHIP_BRYNHILD,
  HELICOPTER_CHINOOK, CHINOOK_BULLET,
  SPACE_MARINE, SPACE_MARINE_BULLET,

}
